name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm and Node.js
        uses: ./.github/actions/setup-pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Buildable test
        run: pnpm build

      - name: Run lint
        run: pnpm lint
