name: Lint

on:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup pnpm Environment
              uses: concertypin/action/pnpm-install@master

            - name: Buildable test
              run: pnpm build

            - name: Run lint
              run: pnpm lint
